### ISSUE TITLE
那个大大呀 我还没启动hook服务他也闪退怎么办呀

### ISSUE THREAD

**Issue by Zfelena** [JsHook-Script-Repo/7c6c28b787cf4f30b0dfca39ab26b0fb#2]
那个大大呀 我还没启动hook服务他也闪退怎么办呀

**Comment by ZYM1016** [comment]
> 那个大大呀 我还没启动hook服务他也闪退怎么办呀

游戏检测root，确认自己有没有做好隐藏

**Comment by shshfyeiejbdhdkwk** [comment]
你好大佬，我这边选择DDDD脚本，注入hook也成功了，进入游戏也能看到悬浮球，点开之后只有简介，没有功能选项，是不是还有东西没下呀。非常感谢

**Comment by Zfelena** [comment]
要开vpn

**Comment by shshfyeiejbdhdkwk** [comment]
> 要开vpn

今天功能还正常吗，在载入见面可以选择开关功能，但是进入游戏画面后就不行了，按钮点不动。

**Comment by love43454** [comment]
需要安装防护模块 启用防护
